# 데이터베이스 연결 설정 (임시 H2 데이터베이스)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 콘솔 사용 설정 (웹에서 DB 확인 가능)
spring.h2.console.enabled=true

# 서버 실행 시마다 테이블 다시 생성
spring.jpa.hibernate.ddl-auto=update